language: node_js
node_js:
- 4.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
- gem install compass
- npm install -g bower grunt-cli
- bower install
before_install:
- openssl aes-256-cbc -K $encrypted_9f3f16b51714_key -iv $encrypted_9f3f16b51714_iv
  -in travis_rsa.enc -out travis_rsa -d
- rvm install 2.2.2
- chmod 600 ~/.ssh/travis_rsa
addons:
  ssh_known_hosts: romulobordezani.com.br
branches:
  only:
  - master
script:
- grunt build
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
notifications:
  email: true
