language: node_js
node_js:
- 4.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
before_script:
- gem install compass
- npm install -g bower grunt-cli
- bower install
before_install:
  - rvm install 2.2.2
  - openssl aes-256-cbc -K $encrypted_b0b2958c016f_key -iv $encrypted_b0b2958c016f_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
addons:
  ssh_known_hosts: romulobordezani.com.br
branches:
  only:
  - master
script:
- grunt build
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
notifications:
  email: true
