language: node_js
node_js:
- '0.10'
before_script:
- gem install compass
- npm install -g bower grunt-cli
- bower install
- grunt build
before_install:
- rvm install 2.2.2
- openssl aes-256-cbc -K $encrypted_ca2cf7ff4d4e_key -iv $encrypted_ca2cf7ff4d4e_iv
  -in travis_rsa.enc -out travis_rsa -d
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: romulobordezani.com.br
branches:
  only:
    - master
